# ===== CONFIG =====

TIMEFRAME = "20m"
VOLUME_MULTIPLIER = 1.5

BODY_PERCENT = 0.89
WICK_PERCENT = 0.30

EMA_PERIOD = 20
BREAKOUT_LOOKBACK = 30

BOT_TOKEN = "8319951690:AAGcrCM60m85TjeaRsoer3JJpD0iKKImTrI"
CHAT_ID ="6259143968"




BANKING = [
     "HDFCBANK.NS","ICICIBANK.NS","SBIN.NS","AXISBANK.NS","KOTAKBANK.NS",
     "INDUSINDBK.NS","BANKBARODA.NS","PNB.NS","FEDERALBNK.NS","IDFCFIRSTB.NS",
     "BANDHANBNK.NS","AUBANK.NS","CANBK.NS","UNIONBANK.NS","YESBANK.NS",
    "BAJFINANCE.NS","BAJAJFINSV.NS","CHOLAFIN.NS","MUTHOOTFIN.NS",
    "HDFCBANK.NS"]

IT= [
    # "TCS.NS","INFY.NS","WIPRO.NS","HCLTECH.NS","TECHM.NS",
    # "LTIM.NS","MPHASIS.NS","COFORGE.NS","PERSISTENT.NS","LTTS.NS",
    # "TATAELXSI.NS","CYIENT.NS","ZENSARTECH.NS","SONATSOFTW.NS","KPITTECH.NS"
    "SONATSOFTW.NS","KPITTECH.NS"
]

AUTO = [
    "MARUTI.NS","TATAMOTORS.NS","M&M.NS","BAJAJ-AUTO.NS","EICHERMOT.NS",
    # "HEROMOTOCO.NS","TVSMOTOR.NS","ASHOKLEY.NS","BHARATFORG.NS","ESCORTS.NS",
    # "BOSCHLTD.NS","MRF.NS","APOLLOTYRE.NS","CEAT.NS","EXIDEIND.NS"
  "TATAMOTORS.NS"]

PHARMA = [
    # "SUNPHARMA.NS","DRREDDY.NS","CIPLA.NS","DIVISLAB.NS","LUPIN.NS",
    # "AUROPHARMA.NS","TORNTPHARM.NS","ALKEM.NS","GLENMARK.NS","BIOCON.NS",
    # "NATCOPHARM.NS","APOLLOHOSP.NS","MAXHEALTH.NS","LALPATHLAB.NS","AJANTPHARM.NS"
    "SUNPHARMA.NS"
]


TRACK_SECTORS = BANKING + IT + AUTO + PHARMA

